title: Hasanjan's Homepage
page-top-title: Hasanjan Yimit
top-section-bg-text: Engineering Geology
home-subtitle: Hasanjan Yimit&ensp;|&ensp;艾山江
copyright-text: '&copy; Hasanjan 2023-2024. All Rights Reserved.'
